// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ApiPresidenciaDR.Application_Layer.Dtos.ScadaDtos;
using ApiPresidenciaDR.Infrastructure_Layer.Data_Access.Models.CommonModels;
using ApiPresidenciaDR.Models.Context.ScadaContext;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

using ApiPresidenciaDR.Application_Layer.Dtos.ScadaDtos.GeneracionUltimas24HorasDto;
using ApiPresidenciaDR.Application_Layer.Dtos.ScadaDtos.UltimosNiveles;

namespace ApiPresidenciaDR.Models.Context.ScadaContext
{
    public partial interface IScadaRepository
    {
        Task<List<GeneracionUltimas24HorasDto>> Generacion24hAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Niveles6MesesDto>> Niveles6MesesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);

        Task<List<Niveles>> NivelCentrales5minutosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Potencia>> PotenciaActiva5MinutoAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);

        Task<List<GeneracionUltimas24HorasDto>> GetGeneracionUltimas24HorasAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);

    }
}
