// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiPresidenciaDR.Models.Context.ScadaContext
{
    public partial class GetGeneracionUltimas24HorasResult
    {
        public int IDCentral { get; set; }
        public string Central { get; set; }
        public string Parametro { get; set; }
        public DateTime? Fecha { get; set; }
        public string Hora { get; set; }
        public double? Generador1 { get; set; }
        public double Generador2 { get; set; }
        public string UnidadMedida { get; set; }
    }
}
