// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiPresidenciaDR.Models.Context.ScadaContext
{
    public partial class GetPotenciaActiva4SegundosResult
    {
        public int IdPotencia { get; set; }
        public string IdLlave { get; set; }
        public string Nombre { get; set; }
        public string Estacion { get; set; }
        [Column("Valor", TypeName = "decimal(18,0)")]
        public decimal? Valor { get; set; }
        public string UnidadMedida { get; set; }
        public int? CalidadDato { get; set; }
        public DateTime? Fecha { get; set; }
    }
}
