// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ApiPresidenciaDR.Application_Layer.Dtos.ScadaDtos.UltimosNiveles;
using ApiPresidenciaDR.Models.Context.ScadaContext;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ApiPresidenciaDR.Models.Context.ScadaContext
{
    public partial interface IscadadbContextProcedures
    {
        Task<List<GetGeneracionUltimas24HorasResult>> GetGeneracionUltimas24HorasAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);

        Task<List<GetUltimosNivelesResult>> UltimosNiveleCentralessAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetNivelCentralesResult>> GetNivelCentralesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetPotenciaActiva1MinutoResult>> GetPotenciaActiva1MinutoAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetPotenciaActiva4SegundosResult>> GetPotenciaActiva4SegundosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetNivel6MesesResults>> GetNiveles6mesesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);

    }
}
