// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiPresidenciaDR.Models.Context.ScadaContext
{
    public partial class Potencia
    {
        public int IDLlave { get; set; }
        public Byte IDCentral { get; set; }
        public string NombreCentral { get; set; }
        public string Generadores { get; set; }
        public Double Valor { get; set; }
        public string UnidadMedida { get; set; }
        public DateTime Fecha { get; set; }
    }
}
