//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Storage;
//using System;
//using System.Collections.Generic;
//using System.Data.Common;
//using System.Linq;
//using System.Threading;
//using System.Threading.Tasks;

//namespace ApiPresidenciaDR.Models.Context.ScadaContext
//{
//    public static class DbContextExtensions
//    {
//        public static async Task<List<T>> SqlQueryAsync<T>(this DbContext db, string sql, object[] parameters = null, CancellationToken cancellationToken = default) where T : class
//        {
//            if (parameters is null)
//            {
//                parameters = new object[] { };
//            }

//            if (typeof(T).GetProperties().Any())
//            {
//                return await db.Set<T>().FromSqlRaw(sql, parameters).ToListAsync(cancellationToken);
//            }
//            else
//            {
//                await db.Database.ExecuteSqlRawAsync(sql, parameters, cancellationToken);
//                return default;
//            }
//        }
//    }

//    public class OutputParameter<TValue>
//    {
//        private bool _valueSet = false;

//        private TValue _valueField;

//        public TValue Value
//        {
//            get
//            {
//                if (this._valueSet)
//                    return _valueField;

//                throw new InvalidOperationException("Value not set.");
//            }
//        }

//        internal void SetValue(object value)
//        {
//            _valueSet = true;

//            _valueField = null == value || Convert.IsDBNull(value) ? default(TValue) : (TValue)value;
//        }
//    }
//}
